---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation
APPLY_FIXES: none
DISABLE_ERRORS: false
ENABLE_LINTERS:
  # Markdown / docs
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWN_LINK_CHECK
  # HTML / CSS / JS
  - HTML_HTMLHINT
  - CSS_STYLELINT
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  # GitHub Actions + YAML
  - ACTION_ACTIONLINT
  - YAML_PRETTIER
  # General formatting hygiene
  - EDITORCONFIG_EDITORCONFIG_CHECKER

FILEIO_REPORTER: false
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
LOG_LEVEL: INFO
MARKDOWN_MARKDOWNLINT_FILE_EXTENSIONS:
  - .md
  - .md.erb
  - .html.md.erb
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
MARKDOWN_MARKDOWN_LINK_CHECK_FILE_EXTENSIONS:
  - .md
  - .md.erb
  - .html.md.erb
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILE_EXTENSIONS:
  - .md
  - .md.erb
  - .html.md.erb
MARKDOWN_REMARK_LINT_FILE_EXTENSIONS:
  - .md
  - .md.erb
  - .html.md.erb
PARALLEL: true
SARIF_REPORTER: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: false
